import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../store';
import axios from 'axios';
import { NULL } from 'sass';

export interface WeatherInfo {
    WeatherInfo: {
    current: { temperature: number; weather_descriptions: string; wind_speed:number; feelslike:number; weather_icons:string;};
    location: { name: string };
    
  }
  status: 'idle' | 'loading' | 'failed';

}

const initialState: WeatherInfo = {

    WeatherInfo: {
        current: {temperature:0,weather_descriptions:"",wind_speed:0,feelslike:0,weather_icons:""},
        location: { name:"" }
      },
  status: 'idle'
};

export const getWeatherInfoAsync = createAsyncThunk(
  'Wather/GetWatherInfo',
  async (CiteName :string, thunkAPI) => {
     var apiReq=`http://api.weatherstack.com/current?access_key=e87cfaf9fe794ed54f7cbdc5d96a4817&query=${CiteName}`;
  //  console.log(apiReq)
     try {
      const response = await axios.get(apiReq)
      const data: any = response.data
      console.log("Weather data");
      console.log(data);
      return data
    } catch (error: any) {
      thunkAPI.rejectWithValue(error.response.data)
    }

  }
);


export const Weather = createSlice({
  name: 'Weather',
  initialState,
  reducers: {
    getWeather :(state,action)=>{
      state.WeatherInfo = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getWeatherInfoAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getWeatherInfoAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.WeatherInfo = action.payload;
      });
  },
});

export const getWeather = (state: RootState) => state.Weather;
export default Weather.reducer;
